/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d228d28d99905f71a3f6ae76820725bc)
interface __BaseEnv_Env {
	ORCHESTRATOR_MODE: "inprocess";
	DEMO_LOGIN_ENABLED: "1";
	SEED_DEMO_DATA: "1";
	RUN_MIGRATIONS_ON_BOOT: "1";
	DEFAULT_MODEL: "openai/gpt-oss-120b";
	CORS_ORIGINS: "http://localhost:3002,https://agentfleet-app.YOUR_SUBDOMAIN.workers.dev";
	EMBEDDINGS_PREWARM: "1";
	DATABASE_SCHEMA: "agentfleet";
	DATABASE_SSL: "1";
	DATABASE_URL: string;
	AUTH_SECRET: string;
	FREE_LLM_BASE_URL: string;
	FREE_LLM_KEY: string;
	AGENTFLEET_API: DurableObjectNamespace<import("./src/index").AgentFleetApi>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "AgentFleetApi";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORCHESTRATOR_MODE" | "DEMO_LOGIN_ENABLED" | "SEED_DEMO_DATA" | "RUN_MIGRATIONS_ON_BOOT" | "DEFAULT_MODEL" | "CORS_ORIGINS" | "EMBEDDINGS_PREWARM" | "DATABASE_SCHEMA" | "DATABASE_SSL" | "DATABASE_URL" | "AUTH_SECRET" | "FREE_LLM_BASE_URL" | "FREE_LLM_KEY">> {}
}
