"""user ownership on agents documents runs

Revision ID: 2fc38a3e8b1b
Revises: 60038d765942
Create Date: 2026-07-16 14:26:55.220387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc38a3e8b1b'
down_revision: Union[str, Sequence[str], None] = '60038d765942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('runs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'runs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'user_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'user_id')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'user_id')
    # ### end Alembic commands ###
