"""user ownership on agents documents runs

Revision ID: 2fc38a3e8b1b
Revises: 60038d765942
Create Date: 2026-07-16 14:26:55.220387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc38a3e8b1b'
down_revision: Union[str, Sequence[str], None] = '60038d765942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicit constraint names (each matches Postgres's own default naming for
    # an unnamed FK) instead of the autogenerated `None`: Base has no
    # naming_convention set, so `drop_constraint(None, ...)` cannot resolve the
    # constraint name on downgrade and raises a CompileError. The names below
    # are the ones Postgres already assigned, so upgrade behaviour is unchanged.
    op.add_column('agents', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'agents_user_id_fkey', 'agents', 'users', ['user_id'], ['id'], ondelete='SET NULL'
    )
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'documents_user_id_fkey', 'documents', 'users', ['user_id'], ['id'], ondelete='SET NULL'
    )
    op.add_column('runs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'runs_user_id_fkey', 'runs', 'users', ['user_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Names pinned to match upgrade() above — see the comment there.
    op.drop_constraint('runs_user_id_fkey', 'runs', type_='foreignkey')
    op.drop_column('runs', 'user_id')
    op.drop_constraint('documents_user_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'user_id')
    op.drop_constraint('agents_user_id_fkey', 'agents', type_='foreignkey')
    op.drop_column('agents', 'user_id')
    # ### end Alembic commands ###
