"""webhooks

Revision ID: 3ebcd6b693ae
Revises: 82e61fa596f6
Create Date: 2026-07-11 22:21:30.874121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3ebcd6b693ae'
down_revision: Union[str, Sequence[str], None] = '82e61fa596f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping analytics_customers,
    # analytics_sales, checkpoints, checkpoint_writes, checkpoint_blobs, and
    # checkpoint_migrations — those tables are created outside models.py (by
    # scripts/seed_analytics.py and the LangGraph Postgres checkpointer
    # respectively), so autogenerate sees them as "unknown" and wants to
    # drop them. Stripped; this migration only creates 'webhooks'.
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('goal_template', sa.Text(), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('secret_prefix', sa.String(length=12), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhooks')
    # ### end Alembic commands ###
