"""agent runtime column

Revision ID: 60038d765942
Revises: fcf2c79da7bc
Create Date: 2026-07-16 09:07:07.200439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60038d765942'
down_revision: Union[str, Sequence[str], None] = 'fcf2c79da7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('runtime', sa.String(length=20), server_default='langgraph', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'runtime')
    # ### end Alembic commands ###
