"""agent mcp_servers

Revision ID: 6a640e8f5f6d
Revises: 71644dfb08f5
Create Date: 2026-07-10 20:09:49.864545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a640e8f5f6d'
down_revision: Union[str, Sequence[str], None] = '71644dfb08f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'agents',
        sa.Column(
            'mcp_servers',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'mcp_servers')
    # ### end Alembic commands ###
