"""workflows table and runs workflow_id

Revision ID: 71f06f2bbf73
Revises: 2fc38a3e8b1b
Create Date: 2026-07-28 17:11:24.222968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71f06f2bbf73'
down_revision: Union[str, Sequence[str], None] = '2fc38a3e8b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.add_column('runs', sa.Column('workflow_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_runs_workflow_id'), 'runs', ['workflow_id'], unique=False)
    # Explicit name (matches Postgres's own default naming for an unnamed FK)
    # instead of the autogenerated `None`: Base has no naming_convention set,
    # so `drop_constraint(None, ...)` cannot resolve the constraint name on
    # downgrade and raises a CompileError. Verified by round-tripping
    # upgrade -> downgrade -> upgrade against the local dev DB.
    op.create_foreign_key(
        'runs_workflow_id_fkey', 'runs', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('runs_workflow_id_fkey', 'runs', type_='foreignkey')
    op.drop_index(op.f('ix_runs_workflow_id'), table_name='runs')
    op.drop_column('runs', 'workflow_id')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
