"""run task attempts and heal log

Revision ID: fae1d462a303
Revises: 71f06f2bbf73
Create Date: 2026-07-29 03:17:57.540116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fae1d462a303'
down_revision: Union[str, Sequence[str], None] = '71f06f2bbf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (autogenerate left these off, which would
    # fail against the 9 existing run_tasks rows) — same pattern as
    # 60038d765942 (agents.runtime) and 6a640e8f5f6d (agents.mcp_servers).
    op.add_column(
        'run_tasks', sa.Column('attempts', sa.Integer(), server_default='1', nullable=False)
    )
    op.add_column(
        'run_tasks',
        sa.Column(
            'heal_log',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_tasks', 'heal_log')
    op.drop_column('run_tasks', 'attempts')
    # ### end Alembic commands ###
